### ISSUE TITLE
support sourcemap

### ISSUE THREAD

**Issue by kazupon** [intlify/bundle-tools#1]

**Comment by mHooshdar** [comment]
Any updates?

**Comment by imShara** [comment]
May we have sourcemap support or just skipping sourcemaps for locale files, but not broke it at all?

```
Sourcemap is likely to be incorrect: a plugin (vite-plugin-vue-i18n) was used to transform files, but didn't generate a sourcemap for the transformation.
Consult the plugin documentation for help.
```

```js
{"version":3,"file":"main.js","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;"}
```

**Comment by gongora92** [comment]
> May we have sourcemap support or just skipping sourcemaps for locale files, but not broke it at all?
> 
> ```
> Sourcemap is likely to be incorrect: a plugin (vite-plugin-vue-i18n) was used to transform files, but didn't generate a sourcemap for the transformation.
> Consult the plugin documentation for help.
> ```
> 
> ```js
> {"version":3,"file":"main.js","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;"}
> ```

Is there any way to solve this? I'm getting this same error while trying to generate sourcemaps for Sentry.

**Comment by kazupon** [comment]
I would really like to support it ...
I'm not currently a full-time OSS developer, but I have plans to continue to support it.
Please wait :pray:

**Comment by JessicaSachs** [comment]
@kazupon how can we (Cypress) help?

**Comment by kazupon** [comment]
Hello! @JessicaSachs  😺 
I tried to support the source map this repo before
https://github.com/intlify/vite-plugin-vue-i18n/pull/33

At the time, I had a hard time mapping the source map retrieved from the rollup to the source map returned by the json and yaml generator.
if I will be possible a little more time, I think I can support the source map, but I need a little **focus time** on it.

If you (Cypress) can support it, I would be really happy. :relaxed:

**Comment by kazupon** [comment]
I've just fixed it and released out `@intlify/vite-plugin-vue-i18n` v3.2.1 
Please check it!

**Comment by gongora92** [comment]
> I've just fixed it and released out `@intlify/vite-plugin-vue-i18n` v3.2.1 Please check it!

Thank you!

**Comment by fcomrqz** [comment]
We are missing a source map with `@intlify/vite-plugin-vue-i18n@3.2.1` on dev mode

### Console Error
DevTools failed to load source map: Could not load content for http://localhost:3000/@vite/client.mjs.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Steps to reproduce
1. Create a new project with `npm init vite@latest my-vue-app -- --template vue`
2. Install vue-i18n with `npm i @intlify/vite-plugin-vue-i18n vue-i18n`
3. Add i18n plugin to `vite.config.js`
4. Run dev mode `npm run dev` to inspect

**package.json**
```.json
{
  "name": "my-vue-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@intlify/vite-plugin-vue-i18n": "^3.2.1",
    "vue": "^3.2.25",
    "vue-i18n": "^9.1.9"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.0.1",
    "vite": "^2.7.12"
  }
}
```

**vite.config.js**
```.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import i18n from '@intlify/vite-plugin-vue-i18n'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), i18n()],
})

```

### Environment
macOS 12.1
Node 14.18.2
npm 8.3.1
Chrome 97
Safari 15.2

_I can see the inlined source map for http://localhost:3000/@vite/client when I don't have installed the plugin, that's why I suspect that it's related._

I don't know how I can help to fix it, I hope somebody can address me.

**Comment by Ragura** [comment]
Can confirm this problem exists, also running macOS 12.1 and tried in Chrome and Safari. If @kazupon has very little time to look into it, perhaps he can point us in the right direction to look for a fix ourselves so we can make a pull request?

**Comment by kazupon** [comment]
> DevTools failed to load source map: Could not load content for http://localhost:3000/@vite/client.mjs.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Hmm 🤔 ,
As for the cause of this, I honestly don't know.
It happens with source map support, so I'm pretty sure that fix is affecting it.
There may be a problem with the way the rollup API is used.

The issue with no support for source map has been resolved. The new issue will be opened as a separate #82 

Thanks!
