### ISSUE TITLE
Failing to process translation values (e.g. with special characters or syntax errors) has terrible error message

### ISSUE THREAD

**Issue by philipp-rudloff-sendcloud** [intlify/bundle-tools#108]
### Reporting a bug?

Whenever vue-i18n via vue-i18n-loader fails to process a translation value with a special character or a syntax error, vue-i18n-loader reports the following generic error message:

> Syntax Error: Final loader (./node_modules/@intlify/vue-i18n-loader/lib/index.js) didn't return a Buffer or String

This happens when the translation value contains special characters (see https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters) or syntax errors (e.g. `An extra closing curly brace after a {placeholder}}.`).

### Expected behavior

The error should at least report where in the file and ideally for which translation key the issue occurs. Currently, only the file is reported like so:

``` ERROR  Failed to compile with 1 error                                                                                                                                                                   5:03:22 PM

 error  in ./src/locales/es-ES.json

Syntax Error: Final loader (./node_modules/@intlify/vue-i18n-loader/lib/index.js) didn't return a Buffer or String


 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
[stack trace omitted because it only includes internal files]
```

### Reproduction

This can be reproduced with any vue-i18n-loader-based setup and a translation file like this:

```json
{
  "An extra closing curly brace after a {placeholder}}.": "An extra closing curly brace after a {placeholder}}."
}
```

### Issue Package

vue-i18n-loader

### System Info

```shell
Binaries:
    Node: 16.15.0 - /usr/bin/node
    Yarn: 1.22.18 - ~/.npm-global/bin/yarn
    npm: 8.8.0 - ~/.npm-global/bin/npm
  npmPackages:
    @intlify/vue-i18n-loader: ^5.0.0 => 5.0.0 
    vue: ^3.2.33 => 3.2.33 
    vue-i18n: ^9.1.9 => 9.1.9
```

### Additional context

I’m reporting this as a bug because it makes migrating a large code base with many translations near impossible. I have to binary-search through translation files to identify which key it vue-i18n is stumbling over.

More examples (each of them will cause a failure):

```json
{
  "Contact info@example.org": "Contact info@example.org",
  "Placeholder {with space}": "Placeholder {with space}",
  "Placeholder with accent: {cafe}": "Placeholder with accent: {café}",
  "An extra closing curly brace after a {placeholder}}.": "An extra closing curly brace after a {placeholder}}."
}
```

Corrected version:

```json
{
  "Contact info@example.org": "Contact info{'@'}example.org",
  "Placeholder {withSpace}": "Placeholder {withSpace}",
  "Placeholder with accent: {cafe}": "Placeholder with accent: {cafe}",
  "An extra closing curly brace after a {placeholder}.": "An extra closing curly brace after a {placeholder}."
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your feedback!

This issue is same as #53

For message formats that cannot be understood by vue-i18n, the `@intlify/message-compiler` can output compile errors. vue-i18n-loader can use these compile errors to generate human The vue-i18n-loader needs to be improved to use these compile errors to output human-readable errors.
