### ISSUE TITLE
error in vue-tsc --noEmit && vite build

### ISSUE THREAD

**Issue by KANekT** [intlify/bundle-tools#121]
### Reporting a bug?

when i build with vite - error

### Expected behavior

[vite-plugin-vue-i18n] Cannot read properties of undefined (reading 'message')
file: D:/DaOffice/intra-ionic/node_modules/twilio-video/package.json
error during build:
TypeError: Cannot read properties of undefined (reading 'message')

### Reproduction
add     "twilio-video": "^2.21.1",
run npm vue-tsc --noEmit && vite build

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 7.36 GB / 15.87 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^4.0.0 => 4.0.0
    vite: ^2.9.0 => 2.9.9
    vue: ^3.2.26 => 3.2.33
    vue-i18n: ^9.2.0-beta.23 => 9.2.0-beta.35
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Sorry, for the delay in my response.

Unfortunately, I could not reproduce your issue.
Could you provide minimum reproduction repo, please?

**Comment by KANekT** [comment]
@kazupon thanck for answer ^-^

i have error in CI with node v14.17.5

i change node to v16.15.0 - error is resolved

**Comment by kazupon** [comment]
I'm glad to hear it.
happy coding :)
