### ISSUE TITLE
Uncaught TypeError: _ctx.$t is not a function

### ISSUE THREAD

**Issue by alireza0sfr** [intlify/bundle-tools#123]
hi there, I want to publish my vue3+vite package to npm but after publishing, I encountered "Uncaught TypeError: _ctx.$t is not a function" in a test project and my package is not working, any suggestions... ?

PS: I'm using options api

here is my vite.configs.js
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueI18n from '@intlify/vite-plugin-vue-i18n'

// https://vitejs.dev/config/
const path = require("path")
export default defineConfig({
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/install.ts'),
      name: 'vcp',
      fileName: (format) => `vcp.${format}.ts`
    },
    rollupOptions: {
      external: ['vue'],
      output: {
        exports: 'named',
        globals: {
          vue: 'Vue',
          vcp: 'Vcp'
        }
      }
    },
  },
  plugins: [
    vue(),
    vueI18n({
      include: path.resolve(__dirname, 'src/assets/translations.ts'),
      compositionOnly: false,
    })
  ],
  server: {
    port: 8080
  },
  resolve: {
    dedupe: ['vue'],
    alias: {
      "~": path.resolve(__dirname, "./src"),
      "@": path.resolve(__dirname, "./src"),
    },
  },
})
```

_Originally posted by @alireza0sfr in https://github.com/intlify/bundle-tools/discussions/122_

**Comment by alireza0sfr** [comment]
I realized that include only accepts JSON and YAML files therefore I added a JSON file for my translations but the issue still remains.

**Comment by kazupon** [comment]
close, I've answered in https://github.com/intlify/bundle-tools/discussions/122#discussioncomment-2844181
