### ISSUE TITLE
Vite 3.0 Release

### ISSUE THREAD

**Issue by exidot** [intlify/bundle-tools#141]
### Clear and concise description of the problem

I'm sorry to bother you, Vite 3.0 has been released, and @intlify/vite-plugin-vue-i18n has limited dependencies on Vite 2.x, so now projects using @intlify/vite-plugin-vue-i18n can't use it vite 3.0, can you upgrade the dependency version?

### Suggested solution

upgrade the vite dependency version

### Validations

- [ ] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kazupon** [comment]
I've just released out vite 3 support version
https://github.com/intlify/bundle-tools/releases/tag/vite-plugin-vue-i18n%405.0.0

**Comment by exidot** [comment]
thanks very much!

**Comment by kazupon** [comment]
Happy coding! :)
