### ISSUE TITLE
vite-plugin-vue-i18n: Cannot find module '@intlify/vite-plugin-vue-i18n/messages' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Ragura** [intlify/bundle-tools#159]
### Reporting a bug?

Using `"@intlify/vite-plugin-vue-i18n": "6.0.0"`

First of all, thank you for the work on this project!

I am following instructions for type support for the messages import in `main.ts` when importing the messages virtual module:
```
import messages from '@intlify/vite-plugin-vue-i18n/messages'
```
Unfortunately I'm still getting the typescript error: "Cannot find module '@intlify/vite-plugin-vue-i18n/messages' or its corresponding type declarations."
The actual building works correctly, it's only typescript complaining.

I have added the type to the compiler options in tsconfig as stated in the docs, which doesn't solve it:
```
"types": [
      "vite/client",
      "unplugin-icons/types/vue",
      "@intlify/vite-plugin-vue-i18n/client"
    ],
```

It works if I add the module declaration to a `shims.d.ts` file like this:
```
declare module '@intlify/vite-plugin-vue-i18n/messages' {
  import { LocaleMessages } from '@intlify/core-base'
  import { VueMessageType } from 'vue-i18n'
  const messages: LocaleMessages<VueMessageType>
  export default messages
}
```

Unfortunately I am not able to reproduce this in a simple project or using a template like Vitesse, where the error does not appear, even though the tsconfig is nearly identical.

### Expected behavior

There should not be a typescript error according to the docs.

### Reproduction

Production project specific

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 81.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    npm: 8.13.1 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmPackages:
    @intlify/vite-plugin-vue-i18n: 6.0.0 => 6.0.0 
    vite: 3.0.4 => 3.0.4 
    vue: ^3.2.37 => 3.2.37 
    vue-i18n: ^9.2.2 => 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by Ragura** [comment]
For some reason rebooting VSCode twice in a row fixed the ts error. My apologies for the false alarm!

**Comment by Shuunen** [comment]
same issue here, but even after multiple reload, VSCode can't manage to find types, thanks for your shim @Ragura
