### ISSUE TITLE
unplugin-vue-i18n : [vite:load-fallback] Could not load vue-i18n/dist/vue-i18n.runtime.esm-bundler.js

### ISSUE THREAD

**Issue by CharlesBT** [intlify/bundle-tools#181]
### Reporting a bug?

Error message returned while doing a `vite build` on the project :
https://stackblitz.com/edit/vitejs-vite-elfdtq?file=package.json

The aim is to be able to use vue-i18n with Vite with Vue^2.7

[vite:load-fallback] Could not load vue-i18n/dist/vue-i18n.runtime.esm-bundler.js (imported by src/main.js): ENOENT: no such file or directory

### Expected behavior

the project should build propely

### Reproduction

https://stackblitz.com/edit/vitejs-vite-elfdtq?file=package.json

### Issue Package

unplugin-vue-i18n

### System Info

```shell
nodejs
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your reporting!
In Vue 2.7, We need to support for vue-i18n-bridge, so as  well as vite-plugin-vue-i18n

**Comment by kazupon** [comment]
I've just fixed in unplugin-vue-i18n v0.6.2
Please check it !

Thanks!

**Comment by CharlesBT** [comment]
I used runtimeOnly: false as workaround in between,

So after removing this workaround, it build correctly, great ! Thanks !
