### ISSUE TITLE
Weird json external file loading

### ISSUE THREAD

**Issue by shaan1974** [intlify/bundle-tools#19]
**Reporting a bug?**

I got a weird behaviour when i add sometime a sub node into my json related to the languages.
The weirdest thing is that when i'm working in dev it's ok , this error only append with the build version.

In the screenshot below, if i remove the node "p" with ( v and z inside ) the error disapear.

**Module versions (please complete the following information):**
 - `@intlify/vue-i18n-loader`: 2.0.3
 - `vue-i18n`: 9.0.0
 - `vue`: ^3.0.11

**Screenshots**
![image](https://user-images.githubusercontent.com/3158745/113484018-8dd59980-94a6-11eb-963a-d277f186c384.png)

End my structure.

Generated code with build

![image](https://user-images.githubusercontent.com/3158745/113484278-b742f500-94a7-11eb-94ad-dd38fcf7b01b.png)

The "undefinediundefined" line is created into the build code.

If i remove the node "p" in my json i got this in source code

![image](https://user-images.githubusercontent.com/3158745/113484210-603d2000-94a7-11eb-8f6c-1ea9f02cf1af.png)

So in the line before $e.render = Me , undefinedundefined is not existing.

By the way thanks for your great work.

Comment.

It's seems that if i put my json file content into "https://jsonformatter.curiousconcept.com/" online tool and after i get the formatted result and i paste it into my json file it's working perfectly. Could be problem of indentation ?

**Comment by PeterAlfredLee** [comment]
@shaan1974  @bradleydwyer 
This problem may be caused by the same reason as #32. 
We now disable the source map of yaml and json file by default to avoid #32 and has released v3.0.0.
Can you test this with v3.0.0 and see what happens? Thanks.

**Comment by kazupon** [comment]
vue-i18n-loader will be deprecated near the future
We can use unplugin-vue-i18n
Thanks
