### ISSUE TITLE
Rollup 3

### ISSUE THREAD

**Issue by lllopo** [intlify/bundle-tools#191]
### Clear and concise description of the problem

I've updated to Rollup 3.0 (actually 3.1.0 as of now) and my installation fails with unsatisfied dependency for Rollup 2.5.0 for unplugin-vue-i18n.

### Suggested solution

Add support for Rollup ^3.0.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kazupon** [comment]
Thank you for your reporting!

Currently, `unplugin-vue-i18n` doesn't support for rollup.
But, We can support for it.
Because `unplugin-vue-i18n` is implemented with the same interface as the rollup provided by unplugin.
It needs to be adjusted a bit for rollup v3, though.

**Comment by lllopo** [comment]
Thanks for your answer. I hope you can sort it out. I have rollup as dependency because of other stuff (incl. a few I wrote myself for my vite projects) and all got rollup 3 support almost immediately. All that left is the unplugin-vue-i18n so I'm looking forward to it.

**Comment by lllopo** [comment]
I got [this](https://github.com/unjs/unplugin/issues/181) answer from the 'unplugin' developer, btw.

**Comment by kazupon** [comment]
Hi!
I've just released unplugin-vue-i18n v0.8.0
please check it!
