### ISSUE TITLE
Error: Unexpected token when using vite plugin

### ISSUE THREAD

**Issue by FireMasterK** [intlify/bundle-tools#196]
### Reporting a bug?

When using the vite plugin with a specific JSON file, the bundler seems to not like it.
I could not reproduce this when importing the file with an import statement, so I believe it is a `vite-plugin-vue-i18n` bug.
The build fails, when you try to 

### Expected behavior

The build should succeed.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-gg8jzs?file=vite.config.js

Run `npm run build`

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Linux 6.0 undefined
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 1.63 GB / 15.00 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Brave Browser: 107.1.45.118
    Chromium: 107.0.5304.110
    Firefox: 106.0.5
  npmPackages:
    @intlify/vite-plugin-vue-i18n: 6.0.3 => 6.0.3 
    vite: 3.2.3 => 3.2.3 
    vue: 3.2.43 => 3.2.43 
    vue-i18n: 9.2.2 => 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by FireMasterK** [comment]
It turns out the `|` character causes issues sometimes, I saw another issue and it mentioned it's used for pluralization. Could a more descriptive error message be added maybe?

**Comment by kazupon** [comment]
Thank you for your reproting!
Sorry, poor message of my OSS.

Error message says:
![image.png](https://volta.s3.fr-par.scw.cloud/image_2a91f76092.png)

In this case,  line 153 on `or.json`, plural messages aren't defineded.
You can resolve, when you will define plural message it in there.

Thanks!
