### ISSUE TITLE
Can't use anchors and aliases in YAML files (issues with linked messages)

### ISSUE THREAD

**Issue by edshen17** [intlify/bundle-tools#206]
### Reporting a bug?

I am trying to reuse parts of my translations and tried using [linked messages](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#linked-messages). Yaml didn't seem to like the `@` symbol so I tried anchors and aliases (`& and *`) but I got an error `Uncaught SyntaxError: Unexpected token ','`. I think the issue is with anchors because if I remove all anchors my app builds again.

Example yaml:
```
button:
  about: &about About
  back: *about
```

When I follow the source, I get something like this:

```
export default {
  "button": {
    ,
    
  }
}
```

### Expected behavior

The yaml file should output following
```
button:
  about: About
  back: About
```

### Reproduction

[Repo](https://github.com/edshen17/vue-18n-alias)

Please check the `locales/en.yml` file.

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 4.97 GB / 15.75 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.52)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^6.0.3 => 6.0.3
    vite: ^3.2.4 => 3.2.4
    vue: ^3.2.45 => 3.2.45
    vue-i18n: ^9.2.2 => 9.2.2
```
```


### Screenshot

_No response_

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, anchors and aliases is not supported for vue-i18n.
yaml is parsed by `@intlify/bundle-utils` parser, but it's so hard to support resolving anchors and alias.
For this reason we do not plan to support it in the future.

Thanks
