### ISSUE TITLE
Support for Vite 4.x

### ISSUE THREAD

**Issue by paceband** [intlify/bundle-tools#209]
### Reporting a bug?

npm ERR! While resolving: @intlify/vite-plugin-vue-i18n@7.0.0
npm ERR! Found: vite@4.0.0
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.0" from the root project
npm ERR!   peer vite@">=2" from vite-plugin-eslint@1.8.1
npm ERR!   node_modules/vite-plugin-eslint
npm ERR!     dev vite-plugin-eslint@"^1.8.1" from the root project
npm ERR!   3 more (vite-plugin-full-reload, @vitejs/plugin-basic-ssl, @vitejs/plugin-vue)

### Expected behavior

Works with Vite 4.x

### Reproduction

vite 4.0.0 in package.json

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
...
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your reporting!

As say docs, vite-plugin-vue-i18n isn't support no longer for Vite 4.
https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#intlifyvite-plugin-vue-i18n

You need to use unplugin-vue-i18n
https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n

Thanks!
