### ISSUE TITLE
vue-i18n.runtime.mjs - no such file or directory

### ISSUE THREAD

**Issue by blwtxc** [intlify/bundle-tools#212]
### Reporting a bug?

Running `vite build` throws error

```bash
[vite-plugin-pwa:build] Could not load vue-i18n/dist/vue-i18n.runtime.mjs (imported by src/modules/i18n.ts): ENOENT: no such file or directory, open 'vue-i18n/dist/vue-i18n.runtime.mjs'
error during build:
Error: Could not load vue-i18n/dist/vue-i18n.runtime.mjs (imported by src/modules/i18n.ts): ENOENT: no such file or directory, open 'vue-i18n/dist/vue-i18n.runtime.mjs'
error Command failed with exit code 1.
```

### Expected behavior

Runs without error and builds project.

### Reproduction

I'm using a template, I built myself, that is based on [Vitesse](https://github.com/antfu/vitesse) by @antfu. It mainly adds Vuetify support. I can't say if 'Vitesse' would throw that error.

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC Processor
    Memory: 4.00 GB / 7.58 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^7.0.0 => 7.0.0 
    rollup: ^3.7.5 => 3.7.5 
    vite: ^4.0.1 => 4.0.1 
    vue: ^3.2.45 => 3.2.45 
    vue-i18n: ^9.2.2 => 9.2.2
```

### Additional context

It's fairly probable that this is caused by some versions-mismatch on my side.
Nevertheless after some digging I found that inside `@intlify/vite-plugin-vue-i18n/lib/index.cjs` and `@intlify/vite-plugin-vue-i18n/lib/index.mjs` on line 93 the `runtimeModule` variable is filled with a string, created by appending `.runtime.mjs` to the module/pkg-name -- in my case `vue-i18n`. For whatever reason the resulting file `vue-i18n.runtime.mjs` does not exist in this pkg in my project. What does exist, is e.g. `vue-i18n.runtime.esm-browser.js`, that -- I think -- might serve the same purpose (?). Adding a test, to see if the `.runtime.mjs` exists and, if not, replace it with `.runtime.esm-browser.js` seems to solve the problem for me for now. I know, that's not an elegant solution but perhaps helps to find one.

### Validations

- [ ] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [ ] Read the README
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your reporting!

I realized that your vite is v4.
docs say, vite-plugin-vue-i18n is only supported up to vite v3. 
https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#%EF%B8%8F-deprecated

If you would use vite v4, you need use unplugin-vue-i18n.
Could you try to use it, please?

**Comment by blwtxc** [comment]
Aah ... I see ... I thought it's some king of mismatch! Thanks for pointing me into the right direction!
Works as expected.
So sorry to have bothered you.
Cheers!

**Comment by kazupon** [comment]
I’m happy to hear your good news.
happy coding! :)
