### ISSUE TITLE
Named interpolation doesn't work when app is built

### ISSUE THREAD

**Issue by Polm90** [intlify/bundle-tools#216]
### Reporting a bug?

I'm using named interpolation to print some strings.
During the app development (while running `npm dev`) everything is worked as expected.
However, if I build the app (using `npm build`) the named interpolation is not replaced anymore, so I can see the values between the { not been replaced.

### Expected behavior

The { } part should be reploaced

### Reproduction

Here is my template:

```html
<template>
  <main class="page-w container-center">
    <div class="wrapper-text item-center">
      <h1 class="title">{{$t("start_page.title")}}</h1>
      <div class="text-v">{{$t('start_page.content', {starTag: "test"})}}</div>
    </div>
  </main>
</template>
```

This is the json file:

```json
{
  "start_page": {
    "title": "Welcome!",
    "content": "Hello {starTag}",
  },
}
```

### Issue Package

unplugin-vue-i18n

### System Info

I'm using:

```shell
node 19.3.0
npm 9.2.0
vite 4.0.4
vue 3.2.45 (with composition api, SFC)
vue-i18n 9.2.2
@intlify/unplugin-vue-i18n 0.8.1
```

### Additional context

You can read more info [here](https://github.com/intlify/vue-i18n-next/issues/1278)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by lex-nel** [comment]
+1

**Comment by ajmas** [comment]
I am seeing this issue too. I had opened a question on Stack Exchange, related to this:

https://stackoverflow.com/questions/75315371/vue-i18n-not-substituting-tokens-in-production-build

**Comment by ajmas** [comment]
So it would appear we need to provide the `runtimeOnly: false` configuration to work deal with this.

The README dos cover this aspect, but until you hit it, it isn't really clear:

> Also, if you do a production build with vite, Vue I18n will automatically bundle the runtime only module. If you need on-demand compilation with Message compiler, you need to set the `runtimeOnly` option to `false`.

**Comment by Polm90** [comment]
@ajmas I confirm that it works with your solution (the flag at false).
I don't understand why this flag as true as default value...

Thank you!

**Comment by Slokilla** [comment]
This fix can't work if you use strict CSP config. Has anyone any idea on how to deal with it ?

**Comment by Slokilla** [comment]
`runtimeOnly=false` will cause the lib to load vue-i18n.esm-bundler.js. This file actually use the "eval()" function. 

Now, as you can read [here](https://vue-i18n.intlify.dev/guide/advanced/optimization.html) in the red note, this file won't work with CSP enabled.

So, i'm stucked here between : 
  - not having pluralization / interpolation when built
  - not having my CSP enabled. 

Note that, with unplugin-vue-i18n 0.7.0, I do not have the interpolation issue. It comes with 0.7.1

**Comment by ajmas** [comment]
The use of the eval is problematic. Is there an open ticket addressing that issue in vue-i18n?

**Comment by arv-asommer** [comment]
Bumb i have the same issue using nuxt 3.7.3 with @nuxtjs/i18n 8.0.0... Can someone help me? :D
I also just installed @intlify/unplugin-vue-i18n(1.5.0) and set runtimeOnly to false... Still does not work though
