### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval'

### ISSUE THREAD

**Issue by theromie** [intlify/bundle-tools#23]
After adding vue add i18n to project and running locally its working fine but when I uploaded build to server I am getting `Refused to evaluate a string as JavaScript because 'unsafe-eval'` error.

Version:
Vue:3
Vue-i18n:^9.1.0

here is i18n.js file

`import { createI18n } from 'vue-i18n';
import en from "./locales/en.json";
import de from "./locales/de.json";

/**
 * Load locale messages
 *
 * The loaded `JSON` locale messages is pre-compiled by `@intlify/vue-i18n-loader`, which is integrated into `vue-cli-plugin-i18n`.
 * See: https://github.com/intlify/vue-i18n-loader#rocket-i18n-resource-pre-compilation
 */

export default createI18n({
  legacy: false,
  globalInjection: true,
  locale: process.env.VUE_APP_I18N_LOCALE || 'en',
  fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'de',
  messages: {
    en: en,
    de: de
  }
});
`

Vue config file
`pluginOptions: {
    i18n: {
      locale: 'en',
      fallbackLocale: 'de',
      localeDir: 'locales',
      enableLegacy: false,
      runtimeOnly: false,
      compositionOnly: false,
      fullInstall: true
    }
  }`

**Comment by kazupon** [comment]
Thank you for your reporting!
I could not reproduce this issue.
Could you provide a reproduction repo, please?

**Comment by EthanLuu** [comment]
I believe this issues occurred when:
1. use i18n in your project.
2. add CSP restrictions and not enable the unsafe-eval in your head tag.
```html
  <meta
      http-equiv="Content-Security-Policy"
      content="script-src 'self';"
  />
```
And this error occurred like below:
![image](https://user-images.githubusercontent.com/27045104/128323153-2b424398-8e94-4222-822b-0a2256b0aff8.png)

After some debugging work, this issue is mainly caused by the `new Function("...")` in `core-base.esm-bundler.js:317`
The translate function will call this and parse the string to a function. This kind of parsing is abandoned when CSP restricted.
Still wondering the solution.

**Comment by kazupon** [comment]
You can resolve with webpack `resolve.alias` config.
the following setting:
```js
module.exports = {
  // ...
  resolve: {
    alias: {
      'vue-i18n': 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js'
    }
  },
  // ...
}
```

The reason why this setting is necessary is as follow URL:
https://github.com/intlify/bundle-tools/tree/main/packages/vue-i18n-loader#why-do-we-need-to-require-the-configuration

**Comment by EthanLuu** [comment]
> You can resolve with webpack `resolve.alias` config.
> the following setting:
> 
> ```js
> module.exports = {
>   // ...
>   resolve: {
>     alias: {
>       'vue-i18n': 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js'
>     }
>   },
>   // ...
> }
> ```
> 
> The reason why this setting is necessary is as follow URL:
> https://github.com/intlify/bundle-tools/tree/main/packages/vue-i18n-loader#why-do-we-need-to-require-the-configuration

Resolved, thanks a lot!

**Comment by shaik4949** [comment]
> You can resolve with webpack `resolve.alias` config. the following setting:
> 
> ```js
> module.exports = {
>   // ...
>   resolve: {
>     alias: {
>       'vue-i18n': 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js'
>     }
>   },
>   // ...
> }
> ```
> 
> The reason why this setting is necessary is as follow URL: https://github.com/intlify/bundle-tools/tree/main/packages/vue-i18n-loader#why-do-we-need-to-require-the-configuration

If i use above, i am getting error:
Invalid options in vue.config.js: "resolve" is not allowed
