### ISSUE TITLE
Switch escodegen to something else. It's dependency "word-wrap" is reported as having a security issue 

### ISSUE THREAD

**Issue by Neogeekmo** [intlify/bundle-tools#257]
### Reporting a bug?

Hello,

Snyk is reporting a security issue on package word-wrap which is part of the dependency tree of escodegen :

```
└─┬ @intlify/bundle-utils/5.4.0_vue-i18n@8.27.2
  └─┬ escodegen@2.0.0
    └─┬ optionator@0.8.3
      └── word-wrap@1.2.3
```

Where word-wrap is reported as having a vulnerability
https://security.snyk.io/package/npm/word-wrap/1.2.3

### Expected behavior

Fix the security issue

### Reproduction

do
`npm ls word-wrap`
and it will print:

```
└─┬ @intlify/bundle-utils/5.4.0_vue-i18n@8.27.2
  └─┬ escodegen@2.0.0
    └─┬ optionator@0.8.3
      └── word-wrap@1.2.3
```

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U        
    Memory: 2.14 GB / 31.69 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.19041.1566

I use pnpm so ...
    "vue": "^2.7.14",
    "vite": "^4.2.1",
    "vue-i18n": "8.27.2",
    "vue-i18n-bridge": "^9.2.2",
    "@intlify/unplugin-vue-i18n": "^0.10.0",
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

I've found out the security issue at github issue of escodegen.
Unfortunately, I could not find it. 😒 
https://github.com/estools/escodegen/issues

I think we should report to the escodegen repo that security issue.
If they can't maintain it, then I guess we will have to fork the escodegen.

**Comment by nicogominet** [comment]
Do you have any update on this @kazupon ?
Thanks

**Comment by kazupon** [comment]
This is upstream issue.
if you want to fix security report issue, you can use overrides / resolutions of package manager.
