### ISSUE TITLE
 ERROR  [unplugin-vue-i18n] Detected HTML in 

### ISSUE THREAD

**Issue by palachX** [intlify/bundle-tools#259]
### Reporting a bug?

I use nuxt 3.4.1
In version unplugin-vue-i18n 0.10.0 i have error

ERROR  [unplugin-vue-i18n]  Detected HTML in 

vesion 0.8.2 work great

I use vue-i18n this:

import {useLocale} from "@/composables/locale";
import messages from '@intlify/unplugin-vue-i18n/messages'

export default defineNuxtPlugin(({vueApp}) => {
    const i18n = createI18n({
        legacy: false,
        globalInjection: true,
        warnHtmlMessage: false,
        locale: useLocale().value,
        messages
    })

    vueApp.use(i18n)

})

### Expected behavior

Not error

### Reproduction

    "@intlify/unplugin-vue-i18n": "^0.10.0",
    "nuxt": "^3.4.0",
    "vue-i18n": "^9.2.2"

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 2.68 GB / 15.82 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: master_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vue-i18n: ^9.2.2 => 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your reporting!

You need to configure `strictMessage: false`.
Please see the option at here:
https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#strictmessage

**Comment by ExEr7um** [comment]
> Thank you for your reporting!
> 
> You need to configure `strictMessage: false`. Please see the option at here: https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#strictmessage

I should mention that if you're using `nuxt-i18n` then you should add this to `i18n` option in `nuxt.config.ts`:
```ts
precompile: {
  strictMessage: false,
}
```

**Comment by palachX** [comment]
I add 
strictMessage: false in createI18n
and  in my  nuxt.config.ts
but in both cases I get  same error

I use vue-i18n and nuxt 3.4.1

**Comment by ExEr7um** [comment]
> I add strictMessage: false in createI18n and in my nuxt.config.ts but in both cases I get same error
> 
> I use vue-i18n and nuxt 3.4.1

So you have it like this, right?

```ts
export default defineNuxtConfig({
  i18n: {
    precompile: {
      strictMessage: false,
    },
  },
})
```

**Comment by palachX** [comment]
> 

I added it a little differently, but I did it now since you wrote, unfortunately the same error in html.

Following the logical path that you suggested, I added it like this and it works)

![image](https://user-images.githubusercontent.com/46408447/232512315-2c76f888-903f-4c29-8fbf-2a241d1fe00b.png)

**Comment by palachX** [comment]
uh, I did it, you can close the error, I hope we helped the same guys as me)

**Comment by lxt-ing** [comment]
I got the same error . 
the project is with electron + vue3 + webpack enviroment .  i use the @inilify/unplugin-vue-i18n/webpack,  but it show error  ERROR [unplugin-vue-i18n] Detected HTML in because  i have html in json file. i try to add strictMessage in options ,but it show another error 
 
![9AD6A12D-ABC2-45c3-BE12-6BBCF1834DC0](https://user-images.githubusercontent.com/33947486/233818486-64a1cdc3-e4b0-4a21-a853-9465d3c720c2.png)

config:
![5E2411EB-974F-45e4-AD44-20E722C02266](https://user-images.githubusercontent.com/33947486/233818504-e0534f2c-0552-4e1b-85ed-79992711dbb6.png)

**Comment by palachX** [comment]
> Я получил ту же ошибку. проект с электронной + vue3 + средой webpack. я использую @inilify/unplugin-vue-i18n/webpack, но он показывает ошибку ERROR [unplugin-vue-i18n] Detected HTML in, потому что у меня есть html в файле json. я пытаюсь добавить strictMessage в опции, но он показывает другую ошибку
> 
> ![9AD6A12D-ABC2-45c3-BE12-6BBCF1834DC0](https://user-images.githubusercontent.com/33947486/233818486-64a1cdc3-e4b0-4a21-a853-9465d3c720c2.png)
> 
> конфигурация: ![5E2411EB-974F-45e4-AD44-20E722C02266](https://user-images.githubusercontent.com/33947486/233818504-e0534f2c-0552-4e1b-85ed-79992711dbb6.png)


It work for me: 
i use another project:
   "@intlify/unplugin-vue-i18n": "^0.10.0",
    "vue": "^3.2.13",
    "vite": "^4.2.2"

<img width="792" alt="image" src="https://user-images.githubusercontent.com/46408447/233822925-dc8101ed-d545-484e-b2b3-b0d0497bc2a8.png">

**Comment by lxt-ing** [comment]
你的邮件我已收到，我会尽快处理

**Comment by palachX** [comment]
@lxt-ing 
Check u include, change on array maybe

**Comment by shenickgc** [comment]
help !

**Comment by LoccBui** [comment]
Love you @lucasboh , work for me in nuxt "^3.6.5",

**Comment by belfortf** [comment]
I'm using the latest version of the tool and nuxt 3.6.5 and if I have:
```
compilation: {
	strictMessage: false,
},
```
I don't see anymore the error message, but the HTML tag gets printed ( all I want to do is to add a <br> tag for formatting my text, I actually see <br> printed out ). What's the solution here ?

**Comment by kazupon** [comment]
Hi!

We need minmal reproduction.
vue-i18n and nuxt i18n has starter

- vue-i18n (bug report): https://github.com/intlify/vue-i18n-next/issues/new?assignees=&labels=Status%3A+Review+Needed&projects=&template=bug-report.yml
- nuxt-i18n (bug report): https://github.com/nuxt-modules/i18n/issues/new?assignees=&labels=pending+triage&projects=&template=bug-report.yml

We hope you would give us your minamal reproduction.

**Comment by LoccBui** [comment]
> I'm using the latest version of the tool and nuxt 3.6.5 and if I have:
> 
> ```
> compilation: {
> 	strictMessage: false,
> },
> ```
> 
> I don't see anymore the error message, but the HTML tag gets printed ( all I want to do is to add a "<br>" tag for formatting my text, I actually see "<br>" printed out ). What's the solution here ?
> 
> escapeHtml: true or false simply changes how the tag is printed out to screen.

You need to use v-html to render html element

**Comment by WebOriginals** [comment]
> Для меня следующая конфигурация решила проблему:
> 
> ```
> export default defineNuxtConfig({
>   i18n: {
>     compilation: {
>       strictMessage: false,
>     },
>   },
> })
> ```
> 
> Правильный ключ конфигурации `compilation` и не `precompile` -> https://v8.i18n.nuxtjs.org/options/misc



> Для меня следующая конфигурация решила проблему:
> 
> ```
> export default defineNuxtConfig({
>   i18n: {
>     compilation: {
>       strictMessage: false,
>     },
>   },
> })
> ```
> 
> Правильный ключ конфигурации `compilation` и не `precompile` -> https://v8.i18n.nuxtjs.org/options/misc

hi, it helped me, thank you

**Comment by pratik149** [comment]
As per official [nuxt/i18n docs](https://i18n.nuxtjs.org/docs/options/compilation#escapehtml):


> If `strictMessage` is disabled by setting it to false, we recommend enabling `escapeHtml` option.

Therefore, now it would be...
```js
export default defineNuxtConfig({
  i18n: {
    compilation: {
      strictMessage: false,
      escapeHtml: true,
    },
  },
})
```

**Comment by ArefAhmadinezhad** [comment]
For me the following config solved the issue:
i18n: {    
     defaultLocale: 'en', 
     detectBrowserLanguage:{
      fallbackLocale: 'en',
     },
     lazy: true,
      compilation: {
        strictMessage: false,
        escapeHtml: true,
      },  
     strategy: 'prefix_and_default',
     langDir: 'locales/',
     locales:[ 
         { code: 'en', language: 'en-US', file: 'en/index.js', dir: 'ltr' }, 
     ]
 },

**Comment by ArefAhmadinezhad** [comment]
For me the following config solved the issue:
 ` i18n: {    
     defaultLocale: 'fa', 
     detectBrowserLanguage:{
      fallbackLocale: 'fa',
     },
     lazy: true,
      compilation: {
        strictMessage: false,
        escapeHtml: true,
      },  
     strategy: 'prefix_and_default',
     langDir: 'locales/',
     locales:[
         { code: 'fa', language: 'ir-IR', file: 'fa/index.js', dir: 'rtl'  }, 
         { code: 'en', language: 'en-US', file: 'en/index.js', dir: 'ltr' }, 
     ]
 },
`

**Comment by taomas** [comment]
> Thank you for your reporting!
> 
> You need to configure `strictMessage: false`. Please see the option at here: https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#strictmessage

thanks，i use it to fixed this error message.
just add config 
`compilation: {
      strictMessage: false,
  },`
in `nuxt.config.js` file.

**Comment by ramazansancar** [comment]
This solved my problem. You need to restart the project for it to work fully.

```ts
export default defineNuxtConfig({
  i18n: {
    compilation: {
      strictMessage: false,
    },
  },
})
```

en.json
```json
{
"test": "Lorem ipsum <span class=\"bold\">Test</span> is simply dummy text of the printing and typesetting industry"
}
```
