### ISSUE TITLE
[Suggestion] In the usage section fix default locale path example

### ISSUE THREAD

**Issue by akires47** [intlify/bundle-tools#260]
### Clear and concise description of the problem

I implement today this plugin on my vite app, and I was dealing with an error not loading the messages using the include on plugin section (vite.config.ts), after a while I detect that the path used didn't have the 'src' part on the path.
Maybe for others devs who copy & paste like me, it's better to include this on the default path and save time.

![image](https://user-images.githubusercontent.com/67715361/231870884-55df7792-3c0f-43ef-97e7-748a07ee272b.png)

### Suggested solution

`'./src/locales/**'`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kazupon** [comment]
Thank you for feddback!
I'll fix example!

**Comment by akires47** [comment]
> Thank you for feddback! I'll fix example!

I submit a PR with the fix, hope it helps.
