### ISSUE TITLE
Nuxt 3: Unexpected token 'export'. 

### ISSUE THREAD

**Issue by LeCoupa** [intlify/bundle-tools#273]
### Reporting a bug?

Hey, I get the same error `unexpected token 'export'.` since a few hours in a blank new Nuxt 3 app and I can't figure it out. Maybe you will see what is wrong. :)

Also, the error differs when I add yaml but I still get an issue.

### Expected behavior

The following component should display `show more`. Instead I get the error in the image below.

```
<template>
  <div>{{ $t('showMore')}} </div>
</template>

<script lang="ts" setup>
</script>

<i18n lang="json">
{
  "en": {
    "showMore": "(Show more)"
  },
  "fr": {
    "showMore": "(Afficher)"
  }
}
</i18n>
```

### Reproduction

 I have created a blank new Nuxt 3 project with the following packages.

```
npm install @nuxtjs/i18n@next --save-dev
npm i @intlify/unplugin-vue-i18n
```

```
// nuxt.config.ts
import VueI18nPlugin from '@intlify/unplugin-vue-i18n'

export default defineNuxtConfig({
  devtools: { enabled: true },

  modules: [
    '@nuxtjs/i18n',
  ],
  vite: {
   plugins: [
      VueI18nPlugin.vite({}),
    ],
  }
})
```

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 189.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Brave Browser: 114.1.52.126
    Safari: 16.1
```

### Screenshot

<img width="1384" alt="CleanShot 2023-06-17 at 23 16 38@2x" src="https://github.com/intlify/bundle-tools/assets/1658644/db0381c2-3cf7-4def-b1ab-f66f890bd5db">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by pfinkbeiner** [comment]
Hm might be the wrong import. 

`import VueI18nPlugin from '@intlify/unplugin-vue-i18n/vite'`

instead of 

`import VueI18nPlugin from '@intlify/unplugin-vue-i18n'`

Then you will most likely run into an issue with `Internal server error: All collection items must start at the same column` If so remove the plugin from additional vite config. Thats how I got it up and running. 

```
// nuxt.config.ts
import VueI18nPlugin from '@intlify/unplugin-vue-i18n/vite'

export default defineNuxtConfig({
  devtools: { enabled: true },

  modules: [
    '@nuxtjs/i18n',
  ],
})
```

**Comment by MasatoHokotaDive** [comment]
I get the same error in both `import VueI18nPlugin from '@intlify/unplugin-vue-i18n/vite'`and `import VueI18nPlugin from '@intlify/unplugin-vue-i18n'`.  I think to need plugins key. I don't get an error the no plugins key, but the translation doesn't work.

```
// nuxt.config.ts
import VueI18nPlugin from '@intlify/unplugin-vue-i18n/vite'

export default defineNuxtConfig({
  devtools: { enabled: true },
  vite: {
    plugins: [
      VueI18nPlugin(),
    ],
  },
  modules: [
    '@nuxtjs/i18n',
  ],
})
```
and
```
// nuxt.config.ts
import VueI18nPlugin from '@intlify/unplugin-vue-i18n'

export default defineNuxtConfig({
  devtools: { enabled: true },
  vite: {
    plugins: [
      VueI18nPlugin.vite(),
    ],
  },
  modules: [
    '@nuxtjs/i18n',
  ],
})
```

**Comment by pfinkbeiner** [comment]
I made a Repository with the bare minimum. You can check it out here [git@github.com:pfinkbeiner/nuxt3-vite-i18n-example.git ](https://github.com/pfinkbeiner/nuxt3-vite-i18n-example) 

Try to clone it and see if it works on your machine. If so, compare the versions and configurations.

**Comment by MasatoHokotaDive** [comment]
@pfinkbeiner I fixed it I use `useI18n().t` instead of `$t` and it solved the problem. Thank you.

**Comment by kazupon** [comment]
close as it's now recommended to use unplugin-vue-i18n

thanks!
