### ISSUE TITLE
failed to load config vite.config.js

### ISSUE THREAD

**Issue by HuangKaiSong** [intlify/bundle-tools#284]
### Reporting a bug?

I followed the documentation to import and use @intlify/unplugin-vue-i18n
But the use of the development server before I started threw a fatal error
![image](https://github.com/intlify/bundle-tools/assets/72957518/47f29352-34d1-492e-b86d-534698cf9ca9)

### Expected behavior

Hope to be up and running

### Reproduction

[https://codesandbox.io/p/sandbox/mutable-paper-pw6y9g](https://codesandbox.io/p/sandbox/mutable-paper-pw6y9g)

### Issue Package

unplugin-vue-i18n

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
    Memory: 1.28 GB / 7.85 GB
  Binaries:
    Node: 18.16.0 - D:\nvm\nodejs\node.EXE
    npm: 9.5.1 - D:\nvm\nodejs\npm.CMD
    pnpm: 8.6.10 - D:\nvm\nodejs\pnpm.CMD
  Browsers:
    Chrome: 115.0.5790.171
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^4.3.2 => 4.3.8
    vue: ^3.2.47 => 3.3.4
    vue-i18n: ^9.2.2 => 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
You need import as `import VueI18nPlugin from '@intlify/unplugin-vue-i18n/vite'`,
not `import VueI18nPlugin from '@intlify/unplugin-vue-i18n'`

Thanks!
