### ISSUE TITLE
Missing dependencies and missing MessageFunctionInternal definition

### ISSUE THREAD

**Issue by macdows** [intlify/bundle-tools#296]
### Reporting a bug?

Just upgraded `@intlify/unplugin-vue-i18n` to version `1.2.0` and I can't build my Vite app anymore because of the following issues:

- Missing definition  for type `MessageFunctionReturn`:

```
node_modules/@intlify/core-base/dist/core-base.d.ts:645:77 - error TS2552: Cannot find name 'MessageFunctionInternal'. Did you mean 'MessageFunctionReturn'?

645 export declare type MessageFunction<T = string> = MessageFunctionCallable | MessageFunctionInternal<T>;
                                                                                ~~~~~~~~~~~~~~~~~~~~~~~
```
By looking into the file I saw this line which I guess is related?
`/* Excluded from this release type: MessageFunctionInternal */`

- Missing dependency `@intlify/devtools-if`:

```
node_modules/@intlify/core-base/dist/core-base.d.ts:8:38 - error TS2307: Cannot find module '@intlify/devtools-if' or its corresponding type declarations.

6 import type { IntlifyDevToolsEmitter } from '@intlify/devtools-if';
7 import type { IntlifyDevToolsHookPayloads } from '@intlify/devtools-if';
8 import { IntlifyDevToolsHooks } from '@intlify/devtools-if';
                                       ~~~~~~~~~~~~~~~~~~~~~~
```

- Missing dependency `@intlify/vue-devtools`:

```
node_modules/@intlify/core-base/dist/core-base.d.ts:10:41 - error TS2307: Cannot find module '@intlify/vue-devtools' or its corresponding type declarations.

10 import type { VueDevToolsEmitter } from '@intlify/vue-devtools';
                                           ~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected behavior

- `MessageFunctionInternal` should be declared somwhere
- `@intlify/vue-devtools` and `@intlify/@intlify/devtools-if` should be added to the dependencies of the package.

### Reproduction

- Go to https://stackblitz.com/edit/github-yae1bq-dxtxjr?file=package.json
- Run `npm run build`
- Verify that the errors listed above are present (there are other unrelated errors that can be ignored)

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 330.63 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 9.6.0 - ~/.nvm/versions/node/v18.13.0/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v18.13.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.4
  npmPackages:
    vite: ^4.4.9 => 4.4.9
    vue: ^3.3.4 => 3.3.4
    vue-i18n: ^9.4.0 => 9.4.0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
close, this issue was fixed at vue-i18n
thanks!
