### ISSUE TITLE
Changelog of unplugin-vue-i18n is not up to date

### ISSUE THREAD

**Issue by bperel** [intlify/bundle-tools#298]
### Reporting a bug?

https://github.com/intlify/bundle-tools/blob/main/packages/unplugin-vue-i18n/CHANGELOG.md doesn't include the latest versions of `@intlify/unplugin-vue-i18n`

### Expected behavior

The changelog should include release notes of the recent versions

### Reproduction

Check https://github.com/intlify/bundle-tools/blob/main/packages/unplugin-vue-i18n/CHANGELOG.md

### Issue Package

unplugin-vue-i18n

### System Info

```shell
N/A
```

### Additional context

I couldn't find release notes in https://github.com/intlify/bundle-tools/releases either

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by rwam** [comment]
BTW @kazupon what's the difference between vs 0.13.0 und 1.3.0 I cannot find any information about the versioning mismatch or did I miss something?

**Comment by m4ss1m0g** [comment]
There are breaking changes?

**Comment by kazupon** [comment]
Thank you for your reporting!

The reason for the lost of changelog is that since v0.13 we only have deps updates. there seems to be a problem with the changelog generation tool we use in intlify/bundle-tools.

There are no breaking changes since v0.13.
