### ISSUE TITLE
it is not installed using npm install

### ISSUE THREAD

**Issue by Gennady77** [intlify/bundle-tools#333]
### Reporting a bug?

I use command from documentation in my vue project -  npm i --save-dev @intlify/unplugin-vue-i18n and got  error

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: starbucks@0.1.0
npm ERR! Found: vue@3.3.8
npm ERR! node_modules/vue
npm ERR!   peerOptional vue@"^2 || ^3.2.13" from @vue/babel-preset-app@5.0.8
npm ERR!   node_modules/@vue/babel-preset-app
npm ERR!     @vue/babel-preset-app@"^5.0.8" from @vue/cli-plugin-babel@5.0.8
npm ERR!     node_modules/@vue/cli-plugin-babel
npm ERR!       dev @vue/cli-plugin-babel@"~5.0.0" from the root project
npm ERR!   peerOptional vue@"*" from @vue/babel-preset-jsx@1.4.0
npm ERR!   node_modules/@vue/babel-preset-jsx
npm ERR!     @vue/babel-preset-jsx@"^1.1.2" from @vue/babel-preset-app@5.0.8
npm ERR!     node_modules/@vue/babel-preset-app
npm ERR!       @vue/babel-preset-app@"^5.0.8" from @vue/cli-plugin-babel@5.0.8
npm ERR!       node_modules/@vue/cli-plugin-babel
npm ERR!         dev @vue/cli-plugin-babel@"~5.0.0" from the root project
npm ERR!   8 more (@vue/cli-plugin-typescript, @vue/server-renderer, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @intlify/unplugin-vue-i18n@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@3.3.11
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.0.0-rc.1" from vue-i18n-bridge@9.8.0
npm ERR!     node_modules/vue-i18n-bridge
npm ERR!       peerOptional vue-i18n-bridge@"*" from @intlify/unplugin-vue-i18n@1.6.0
npm ERR!       node_modules/@intlify/unplugin-vue-i18n
npm ERR!         dev @intlify/unplugin-vue-i18n@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/gennadiy.kondratev/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2023-12-14T06_40_39_566Z-debug-0.log

### Expected behavior

It should be installed :)

### Reproduction

run command in your vue project npm i --save-dev @intlify/unplugin-vue-i18n

### Issue Package

unplugin-vue-i18n

### System Info

```shell
node - 16
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your reporting!

Node v16 was already EOL.
Please use Node v18 or later

Thanks!
