### ISSUE TITLE
nuxt3国际化报错

### ISSUE THREAD

**Issue by Jing-sir** [intlify/bundle-tools#359]
### Reporting a bug?

我在nux3中国际化使用这个插件去解析.yml文件貌似和组件中的<i18n>冲突报错了，不知道怎么解决

### Expected behavior

期望这个问题能解决

### Reproduction

https://github.com/Jing-sir/nuxt3--i18n.git, 项目仓库地址
项目源码
[nuxt3--i18n-main.zip](https://github.com/intlify/bundle-tools/files/15048520/nuxt3--i18n-main.zip)

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 327.23 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
  npmPackages:
    vue: ^3.4.21 => 3.4.21
```

### Additional context

<img width="1141" alt="image" src="https://github.com/intlify/bundle-tools/assets/31515500/c980a15f-ce0a-4774-9537-2521b4b86054">
我在nuxt3中配置了国际化文件，然后抽离了全局的语言文件单独放在了lang文件夹下面，并重写了i18n配置文件
<img width="1472" alt="image" src="https://github.com/intlify/bundle-tools/assets/31515500/7bcfdce9-d657-41df-ba70-78d9bf3e4501">
我是使用了@intlify/unplugin-vue-i18n/vite这个插件去处理lang文件下下面的.yml文件，
<img width="1295" alt="image" src="https://github.com/intlify/bundle-tools/assets/31515500/d06d13ec-49af-4cb9-ba0a-b9129cfad1a4">
但是好像和组件中的<i18n></i18n>标签冲突了，报错
<img width="1451" alt="image" src="https://github.com/intlify/bundle-tools/assets/31515500/89302aa4-2338-4600-9c5a-12e45867dd8d">
我如果干掉nuxt.config.ts中的vite plugins这个插件就不会报错，并把i18n.config.ts文件引入语言文件换成.json格式就不会报错了，但是我想在组件外的语言配置.yml格式，我不知道是我哪里配置的问题还是代码写错了，我找了所有的文档都没有解决这个问题，
麻烦帮帮我，谢谢

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your reporting!

You can add `lang="yaml"` attribute to `<i18n>`
Thanks!
