### ISSUE TITLE
 Is it possible to make a linkage with i18n Ally  

### ISSUE THREAD

**Issue by a982246809** [intlify/bundle-tools#361]
### Clear and concise description of the problem

 Is it possible to make a linkage with i18n Ally  

### Suggested solution

 Is it possible to make a linkage with i18n Ally  

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kazupon** [comment]
i18n ally has linked already on vue-i18n docs
https://vue-i18n.intlify.dev/ecosystem/tools.html#i18n-ally

Thanks!

**Comment by a982246809** [comment]
What I mean is, is it possible to add hard decoding?
我的意思是 , 是否可以增加硬解码
![image](https://github.com/intlify/bundle-tools/assets/56909676/aab7a452-d9c4-405d-b2c1-44afcfe451a4)
