### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/.vite/vue-i18n.js?v=2c415b54' does not provide an export named 'useI18n'

### ISSUE THREAD

**Issue by Power-tile** [intlify/bundle-tools#4]
Hi, I got this error ```
Uncaught SyntaxError: The requested module '/node_modules/.vite/vue-i18n.js?v=2c415b54' does not provide an export named 'useI18n' ``` in my browser console when I am integrating i18n with Vite. I am using Vite 2.3.8 and @intlify/vite-plugin-vue-i18n 2.3.0. Below are my files:

```./vite.config.js```:
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path'
import vueI18n from '@intlify/vite-plugin-vue-i18n'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueI18n({
      include: path.resolve(__dirname, './src/locales/**')
    })
  ]
})
```
```./src/main.js```:
```js
import { createApp } from 'vue'
import { createI18n } from 'vue-i18n'
import App from './App.vue'

import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'

const i18n = createI18n({
    locale: [
        'en',
        'zh',
    ]
})

createApp(App).use(i18n).mount('#app')
```
```./src/App.vue```:
```vue
<template>
  <!-- -->
  <div> {{ t("hello") }}
</template>

<script>
export default {
  name: 'App',
  // ...
};
</script>

<script setup>
import CourseMapView from './components/CourseMapView.vue';
import CourseMapEdit from './components/CourseMapEdit.vue';

import { useI18n } from 'vue-i18n';
const { t, locale } = useI18n({
  locale: 'en'
});
</script>

<style>
</style>
```
```./src/locales/en.yaml```:
```yaml
hello: "Hello, World!"
```
How can I solve this problem? Thanks!

**Comment by Power-tile** [comment]
I solved the problem! I tried commenting out the code that throws error in ```App.vue```, and it prompted that it cannot find a module named ```createI18n```.

I directly installed ```vite-plugin-vue-i18n``` package via ```yarn```, which gave me the warning that ```vue-i18n``` as a peer dependency is not installed. Thus I ran ```yarn add vue-i18n --save```.

However, as I was wandering in the migration guide of ```vue-i18n``` from v8 to v9, I realized that v9 supports Vue 3.0 and introduces a change from ```new I18n()``` to ```createI18n()```. I changed the ```vue-i18n``` to ```vue-i18n@next``` and it no longer throws error.

Is it possible to assign ```vue-i18n``` as a dependency instead of a peer dependency in npm, so that the version required for ```vue-i18n``` is automatically handled when installing ```vite-plugin-vue-i18n```?

P.S. Though no error is thrown, I still had a bunch of warnings and the locale thing not working... I will open another issue. Thanks :D

**Comment by kazupon** [comment]
> However, as I was wandering in the migration guide of `vue-i18n` from v8 to v9, I realized that v9 supports Vue 3.0 and introduces a change from `new I18n()` to `createI18n()`. I changed the `vue-i18n` to `vue-i18n@next` and it no longer throws error.

I would like to consider your feeback.
Happy hacky coding! :)
