### ISSUE TITLE
[@intlify/unplugin-vue-i18n] `@typescript-eslint/typescript-estree` should be moved to devDependencies

### ISSUE THREAD

**Issue by stefanprobst** [intlify/bundle-tools#401]
### Reporting a bug?

because `@intlify/unplugin-vue-i18n` ships with `@typescript-eslint/typescript-estree` v7 pinned as a dependency, `typescript-eslint` complains about missing support for typescript 5.6 in my project even though i have explicitly installed `@typescript-eslint/typescript-estree` 8.13.0.

this is with `pnpm`.

### Expected behavior

`@typescript-eslint/scope-manager` and `@typescript-eslint/typescript-estree` should be`devDependencies` here: 
https://github.com/intlify/bundle-tools/blob/main/packages/unplugin-vue-i18n/package.json#L31-L32

### Reproduction

seems unnecessary here

### Issue Package

unplugin-vue-i18n

### System Info

```shell
System:
    OS: Linux 6.8 KDE neon 6.2 6.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz
    Memory: 19.48 GB / 31.29 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 22.11.0 - ~/.local/share/pnpm/node
    npm: 10.9.0 - ~/.local/share/pnpm/npm
    pnpm: 9.12.3 - ~/.local/share/pnpm/pnpm
    bun: 1.1.34 - ~/.bun/bin/bun
  npmPackages:
    vite: ^5.4.10 => 5.4.10 
    vue: ^3.5.12 => 3.5.12 
    vue-i18n: ^10.0.4 => 10.0.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by ptdev** [comment]
Hi,

Also getting some issues with this when running the latest Nuxt version. The warnings are:


```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.3

Please only submit bug reports when using the officially supported version.
```

Cheers

**Comment by mateusznarowski** [comment]
My temporary “solution” is to hide this message, I have added the following in `package.json`, and after reinstalling the packages the message disappeared

```json
{
  ...
  "pnpm": {
    "overrides": {
      "@typescript-eslint/typescript-estree": "8.13.0"
    }
  }
}
  ```
