### ISSUE TITLE
Hot Module Reloading not working

### ISSUE THREAD

**Issue by clement-escolano** [intlify/bundle-tools#41]
### Reporting a bug?

I use vue-i18n v9 in a vite project and hot module reloading is not working: the page refreshes every time.
I followed the [documentation for hot module reloading for the v8](https://kazupon.github.io/vue-i18n/guide/hot-reload.html#basic-example), and changed the variable name to `import.meta.hot` as per [vite documentation](https://vitejs.dev/guide/api-hmr.html).

### Expected behavior

The translation should be updated without refreshing the page.

### Reproduction

I created this repository to reproduce the issue: https://github.com/clement-escolano/vue-i18n-hmr-vite.
The first commit is a basic vite project generated with `vue-ts` template. The second commit updates vue to the latest version, install vue-i18n to the latest version and try to set up HMR.
Once the repository is cloned and dependencies installed, you should run `npm run dev`, click on the counter button in the web page (http://localhost:3000), then update the translation in `src/locales/en.json` then see that the counter button is reset and the translation updated.

### System Info

```shell
Vue: 3.2.4
vue-i18n: 9.2.0-beta.3
```

### Additional context

I read the other issues about HMR not working but did not manage to apply to my case. Some issues mention version 9.2.0 should fix it but as described here, I used version 9.2.0 in beta and it is still the case.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by clement-escolano** [comment]
Thank you for your transfer. Are you sure this is related to `@intlify/vite-plugin-vue-i18n` though? I did not use it in my project (maybe I should?).

**Comment by clement-escolano** [comment]
OK thank you I see.
HMR without page reload would be a huge bonus for the developer experience so I am looking all options.
I tried to set up `@intlify/vite-plugin-vue-i18n` plugin but HMR seems not to work (page reload again). I will look into it further more.

**Comment by kazupon** [comment]
Fixed in v6.0.1 
https://github.com/intlify/bundle-tools/releases/tag/vite-plugin-vue-i18n%406.0.1
