### ISSUE TITLE
Use optional peerDependency to ensure latest @intlify/vue-i18n-loader is used with Vue I18n v9

### ISSUE THREAD

**Issue by WIStudent** [intlify/bundle-tools#50]
### Clear and concise description of the problem

According to the [README](https://github.com/intlify/bundle-tools/tree/main/packages/vue-i18n-loader), the latest @intlify/vue-i18n-loader requires Vue I18n v9:
> This package of @intlify/bundle-tools is for Vue I18n v9 or later!
> The version for Vue I18n v8.x is now in @intlify/vue-i18n-loader v1.x!

This should be enforced in the package.json.

### Suggested solution

Use [optional peerDependency](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) to require v9 if vue-i18n is installed.
```json
{
  "peerDependencies": {
    "vue-i18n": "^9.0.0"
  },
  "peerDependenciesMeta": {
    "vue-i18n": {
      "optional": true
    }
  }
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kazupon** [comment]
I've fixed and released out!
Please check it!
Thanks!
