### ISSUE TITLE
Cannot use @ in translated message

### ISSUE THREAD

**Issue by josepaiva94** [intlify/bundle-tools#53]
### Reporting a bug?

If I use a JSON like

```json
{
  "bug": "@s are not working"
}
```

the following error appears

```
Uncaught Error: Module build failed: Error: Final loader (./node_modules/@intlify/vue-i18n-loader/lib/index.js) didn't return a Buffer or String
```

### Expected behavior

Printing `@s are not working`

### Reproduction

Use a JSON like

```json
{
  "bug": "@s are not working"
}
```

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.20.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Chromium: 94.0.4606.81
    Firefox: 93.0
  npmPackages:
    vue: ^3.0.0 => 3.2.20 
    vue-i18n: ^9.1.0 => 9.1.9
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by visualjerk** [comment]
What do you think about making special-characters configurable? Something like:

```js
VueI18n.createI18n({
  messages,
  specialCharacters: {
    linked: '~@',
  }
})
```

**Comment by Ev357** [comment]
> What do you think about making special-characters configurable? Something like:
> 
> ```js
> VueI18n.createI18n({
>   messages,
>   specialCharacters: {
>     linked: '~@',
>   }
> })
> ```

Hi. Is this fixed? I can't get it to work...

**Comment by pgorji91** [comment]
> What do you think about making special-characters configurable? Something like:
> 
> ```js
> VueI18n.createI18n({
>   messages,
>   specialCharacters: {
>     linked: '~@',
>   }
> })
> ```

Hi, I can't also get it to work! literal interpolation also doesn't work for me!

**Comment by MickL** [comment]
Use [Literal interpolation](https://vue-i18n.intlify.dev/guide/essentials/syntax#literal-interpolation): `{'@'}`
