### ISSUE TITLE
SFC and  Cannot translate the value of keypath...

### ISSUE THREAD

**Issue by Kouty** [intlify/bundle-tools#6]
This is not exactly an issue of vue-i18n-loader, I am writing it as a reminder for others that may face this problem:
if, inside a single file component, you get the error "Cannot translate the value of keypath...", it may be cause by npm cache.

Solution:
- Check, double check that your vue-i18n-loader has been properly configured
- Add a syntax error inside the `<i18n>{...}</i18n>` tag
- Check that webpack does not compile because the loader complains about the syntax error (if it doesn't, than you didn't configure properly the vue-i18n-loader inside webpack config file)
- Remove the syntax error
- **Remove node_modules folder (the whole folder, not just the i18n folders)**
- **run npm cache clean**
- run npm install

After that, it worked for me (and my colleagues facing the same problem).

**Comment by kazupon** [comment]
vue-i18n-loader will be deprecated near the future
We can use unplugin-vue-i18n
Thanks
