### ISSUE TITLE
Support multiple src

### ISSUE THREAD

**Issue by fredarchimed** [intlify/bundle-tools#7]
Hello,

To localize the application, I need to send the JSON files to a translator. I can't send whole components with template, css and script.
The tag <i18n src="...."> works perfectly but I'd like to have multiple sources. I have a 'common.json' with the standard strings and 'myComponent.json' for the specific ones.
I tried to add 2 tags i18n unfortunately.

Is there a way to import multiple json files for 1 component?
Thanks.

**Comment by kazupon** [comment]
vue-i18n-loader will be deprecated near the future
We can use unplugin-vue-i18n
Thanks
