### ISSUE TITLE
Cannot use with vue-class-component

### ISSUE THREAD

**Issue by SniperJoe** [intlify/bundle-tools#74]
### Reporting a bug?

In case of Options API vue-i18n-loader parses the ```<i18n></i18n>``` section and generates code that puts the result into component object itself. It works for Options API + JS, but breaks when using vue-class-component because in that case component options are not the component object itself, but it's "__o" property. 

### Expected behavior

Code generated by vue-i18n-loader checks if __o prop exists on the component object and puts translations into it if it does. 

### Reproduction

https://github.com/SniperJoe/vue-i18n-loader-repro

### Issue Package

vue-i18n-loader

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 2.01 GB / 31.35 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 12.21.0 - /usr/bin/node
    npm: 8.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 92.0
  npmPackages:
    @intlify/vue-i18n-loader: ^3.2.0 => 3.3.0 
    vue: ^3.2.0 => 3.2.21 
    vue-i18n: ^9.2.0-beta.11 => 9.2.0-beta.17 
    webpack: ^5.44.0 => 5.62.1
```

### Additional context

The workaround I use is to edit bundle-utils/lib/json.js: 
```js
<..>
                        generator.push(`${exportSyntax} function (Component) {`);
                        generator.indent();
                        generator.pushline(`const newI18N = (${componentNamespace}__o ? ${componentNamespace}__o.${variableName} : ${componentNamespace}${variableName}) || []`);
                        generator.pushline(`${componentNamespace}${variableName} = ${componentNamespace}${variableName} || []`);
                        generator.push(`newI18N.push({`);
                        generator.indent();
                        generator.pushline(`"locale": ${JSON.stringify(localeName)},`);
                        generator.push(`"resource": `);
<..>
                        generator.push(`if (${componentNamespace}__o) {`);
                        generator.indent();
                        generator.push(`${componentNamespace}__o.${variableName} = newI18N;`);
                        generator.deindent();
                        generator.push(`} else {`);
                        generator.indent();
                        generator.push(`${componentNamespace}${variableName} = newI18N;`);
                        generator.deindent();
                        generator.push(`}`);
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by SniperJoe** [comment]
P. S. I've set "Issue Package" to "vue-i18n-loader", but in fact I'm not sure.

**Comment by kazupon** [comment]
Thank you for your reporting!

I tried to reproduce using your repo, but unfortunately, I could not reproduce it 😞 
Could you give us the reproduction minimum repo that is forked the below link repo, please?  🙏 
https://github.com/intlify/vue-next-webpack-preview

**Comment by SniperJoe** [comment]
Sure! Please take a look: https://github.com/SniperJoe/vue-next-webpack-preview

Had to update few packages, including Webpack, as vue-class-component requires ts-loader@^9 and ts-loader@^9 requires Webpack 5.

**Comment by kazupon** [comment]
Thank you for your reproduction code!
I've just tried to confirm this issue. and I could understand this issue.

Oh, I didn't know that in vue-class-component, options passing from the vue runtime are treated in a special way.
so, I had not implemented i18n custom blocks for vue-class-component.

This issue needs to be dealt with with the generator on the `bundle-tools`.

However, vue-class-component may not be used by everyone, in vue-i18n-loader we need to add `useClassComponent` options. This will allow us to control the code generation by the generator and use i18n custom blocks in vue-class-component as well.

**Comment by SniperJoe** [comment]
@kazupon please take a look at the PR

**Comment by kazupon** [comment]
@SniperJoe 
Once again, Thank you for your contribution! ❤️ 
I've just released vue-i18n-loader latest version. 🚀 
https://github.com/intlify/bundle-tools/releases/tag/vue-i18n-loader%404.1.0

Please check it! 
```sh
npm install --save-dev @intlify/vue-i18n-lader
```

**Comment by SniperJoe** [comment]
@kazupon it works! 
Thank you very much for collaboration :smiley:
