### ISSUE TITLE
Unify the implementations for each bundler with unplugin

### ISSUE THREAD

**Issue by kazupon** [intlify/bundle-tools#76]
### Clear and concise description of the problem

We are maintaining plugins/loaders for the following bundlers at this repo.

- vite: `@intlify/vite-puglin-vue-i18n`
- webpack: `@intlify/vue-i18n-loader`
- rollup: `@intlify/rollup-plugin-vue-i18n`

The implementation of these plugins is almost identical. And every time a feature is added to each one we have to implement and release it.
We have maintenance costs.

### Suggested solution

We should maintain with using `unplugin`
This is dealt with all of the bundlers we offer.

- unplugin
https://github.com/unjs/unplugin

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by omnjpa27516** [comment]
we need these two features to replace vite-plugin-vue-i18n:
1. [petite-vue-i18n support](https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#for-petite-vue-i18n)
2. [useVueI18nImportName](https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#usevuei18nimportname-experimental)

@kazupon
