### ISSUE TITLE
dateTimeFormat

### ISSUE THREAD

**Issue by TwanoO67** [intlify/bundle-tools#8]
Hello here,

Is it possible to use <i18n> tag to host the date translation?

If so, how does it work ?
because I tried in my project, and $d doestn't seems to find my variables defintions.

Regards,
Antoine

**Comment by PeterAlfredLee** [comment]
Hi, @TwanoO67 
Could you give us the reproduction code or repo, please?

**Comment by TwanoO67** [comment]
Hi,
I'm sorry but 2 years later I don't remember about the related project ^^

**Comment by PeterAlfredLee** [comment]
OK. I'll close this issue for now.
Feel free to reopen if you encountered this again.
