### ISSUE TITLE
Peer dependency conflict with vue-i18n@next

### ISSUE THREAD

**Issue by Vercoutere** [intlify/bundle-tools#83]
### Reporting a bug?

When trying to install @intlify/vite-plugin-vue-i18n in a project with the latest release of the Vue3 compatible build of vue-i18n, an error is thrown.

```
npm install @intlify/vite-plugin-vue-i18n -D
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @intlify/vite-plugin-vue-i18n@3.2.1
npm ERR! Found: vue-i18n@9.2.0-beta.30
npm ERR! node_modules/vue-i18n
npm ERR!   dev vue-i18n@"^9.2.0-beta.30" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional vue-i18n@"^9.0.0" from @intlify/vite-plugin-vue-i18n@3.2.1
npm ERR! node_modules/@intlify/vite-plugin-vue-i18n
npm ERR!   dev @intlify/vite-plugin-vue-i18n@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue-i18n@9.1.9
npm ERR! node_modules/vue-i18n
npm ERR!   peerOptional vue-i18n@"^9.0.0" from @intlify/vite-plugin-vue-i18n@3.2.1
npm ERR!   node_modules/@intlify/vite-plugin-vue-i18n
npm ERR!     dev @intlify/vite-plugin-vue-i18n@"*" from the root project
```

You can force the installation using the `--force` flag. However, I wouldn't expect that to be necessary and thus consider this to be an issue.

### Expected behavior

The vue-i18n docs specifically refer to using the vue-i18n build (v9) provided under the intlify domain for Vue3 compatibility.
The docs for this version of vue-i18n mention installing the package using `npm i vue-i18n@next`, and those same docs reference @intlify/vite-plugin-vue-i18n for bundling. I would expect both to be compatible.

### Reproduction

Create a new project and install vue-i18n@next followed by @intlify/vite-plugin-vue-i18n.

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 813.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 7.24.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.76
    Firefox: 96.0.2
    Safari: 15.0
  npmPackages:
    vite: ^2.7.13 => 2.7.13
    vue: ^3.2.27 => 3.2.29
    vue-i18n: ^9.2.0-beta.30 => 9.2.0-beta.30
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
I've fixed it
we can use `@intlify/vite-plugin-vue-i18n@3.4.0`
thanks!
